.\"     Title: fanorona
.\"    Author: Thierry Randrianiriana
.\"      Date: August 10, 2007
.\"        Id: $Id: fanorona.1 96 2007-09-02 05:44:54Z thierry $
.\"
.TH "fanorona" "6" "August 10, 2007" "" ""
.SH "NAME"
fanorona - board game from Madagascar
.SH "SYNOPSIS"
.HP 8
\fBfanorona\fR [\fB\-\-help\fR] [\fB\-\-version\fR] [\fB\-\-single\fR |\ \fB\-s\fR]
.SH "DESCRIPTION"
.PP
Fanorona is the national board game in Madagascar.
.PP
.SH "OPTIONS"
.PP
These programs follow the usual
GNU
command line syntax, with long options starting with two dashes (`\-'). A summary of options is included below.
.PP
\fB\-?\fR \fB\-\-help\fR
.RS 4
Show description of options.
.RE
.PP
\fB\-s \fB\-\-single\fR
.RS 4
Play against the program.
.RE
.SH "HOMEPAGE"
http://home.gna.org/fanorona/
.SH "AUTHOR"
This manual page was written by Thierry Randrianiriana <randrianiriana@gmail.com>,
for the Debian project (but may be used by others).
.SH "COPYRIGHT"
Copyright \(co 2007-2011 Thierry Randrianiriana
.br
